apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app: pystok-website
  name: pystok-website
spec:
  rules:
  - host: pystok.demo.lintops.tech
    http:
      paths:
      - backend:
          serviceName: pystok-website
          servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pystok-website
  name: pystok-website
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: pystok-website

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pystok-website
  name: pystok-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pystok-website
  template:
    metadata:
      labels:
        app: pystok-website
    spec:
      containers:
        - image: kamsz/pystok-demo-website
          name: pystok-website
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
